baseURL = "/"
languageCode = "en-us"
title = "N3tLabs"
theme = "hugo-hero-theme"
#googleAnalytics = ""
disableKinds = ["taxonomy"]
summaryLength = "60"

[params]
favicon = "/images/n3tlabs-logo.png"

[params.homepage_meta_tags]
   meta_description = "N3tLabs - Private infrastructure for experimental crypto & AI systems"
   meta_og_title = "N3tLabs"
   meta_og_type = "website"
   meta_og_url = "https://n3tlabs.io"
   meta_og_image = "https://n3tlabs.io/images/n3tlabs-logo.png" 

[[menu.main]]
        name="Home"
        url="/"
        weight = 1

[[menu.main]]
        name="Lab"
        url="/lab"
        weight = 2
