baseURL = "https://n3tlabs.io/"
languageCode = "en-us"
title = "N3tLabs"
theme = "hugo-hero-theme"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
summaryLength = "60"

[params.homepage_meta_tags]
   meta_description = "N3tLabs Chainlink Data Provider"
   meta_og_title = "N3tLabs"
   meta_og_type = "website"
   meta_og_url = "https://n3tlabs.github.io"
   meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"

[[menu.main]]
        name="Home"
        url="/"
        weight = 1
[[menu.main]]
        name="About"
        url="/#about"
        weight = 2

[[menu.main]]
        name="Services"
        url="/#services"
        weight = 3

[[menu.main]]
        name="Contact"
        url="/contact"
        weight = 4
